fedoraurl: "http://PATHTOYOURFEDORA"
username: "FEDORAUSERNAME"
password: "FEDORAPASSWORD"
collection_namespace: "PARENTNAMESPACEOFCOLLECTION"
datastream: "DATASTREAM"
start: "yyyy-MM-dd"
end: "yyyy-MM-dd"atdd